### ISSUE TITLE
PUC request: Light version for banner use only.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/prebid-universal-creative#15]
Is it possible to run a light version of cdn.jsdelivr.net/npm/prebid-universal-creative@0.3.0/dist/creative.js  

As code per usage use, so for banner, video, mobile ... each with their own optimized .js

**Comment by bretg** [comment]
Would like to take suggestions (or PRs) about how to structure this repo so that the various use-cases could be combined or separate as desired. Would prefer to avoid too many versions of the creative out on the open source CDN, but it would be fine to have creative.js, creative-banner.js, creative-native.js, creative-mobile.js, and any combinations needed. 

Requirements confirmatiopn wanted as well: what combinations are valid? i.e. should we have creative-banner-native.js, creative-banner-mobile.js, creative-mobile-native.js?

**Comment by GLStephen** [comment]
Just to bring up a point to consider. What's the relative uncached download vs cached rate of the current script? If we had an idea of that, then we'd have an idea of the relative value of this optimization. At least part of the value of using a third party CDN is that it allows for long cache TTLs on the objects and with enough widespread Prebid usage we would expect the download hit to be shared across sites and to have a high cache rate *across* sites for each user.

That aside, in terms of approach, if the concern is execution or parsing then an approach similar to creative.js?load=banner,native,amp,mobile-banner could maximize flexibility with minimal downside *if* the primary concern is execution or parse time and not code size.  There may even be a way to reconfigure a universal creative code with targeting parameters or other information that flows from Prebid, I haven't dug into code and capabilities enough to know for sure it would work.

If the primary concern is size, then we need to make sure we aren't trading size for uncached downloads.
