### ISSUE TITLE
why ClickTracker is not firing in web ?

### ISSUE THREAD

**Issue by montu1996** [prebid/prebid-universal-creative#88]
i checked that click tracker is not being fired in web and i checked in code also, click trackers is fire only when env mobile-app.

below are file link:

https://github.com/prebid/prebid-universal-creative/blob/master/src/nativeTrackerManager.js
https://github.com/prebid/prebid-universal-creative/blob/master/src/nativeAssetManager.js

**Comment by wqi1972** [comment]
I found same issue, and believe I found the reason.
If the <a> is setup with addition html tag, such as:
<a href="%%CLICK_URL_UNESC%%%%PATTERN:hb_native_linkurl%%" target="_blank" class="pb-click" pbAdId="%%PATTERN:hb_adid%%"><p>%%PATTERN:hb_native_title%%<p></a>
then when click event fires, the <p> tag is the event.target, instead of the <a> tag, so the code inside function `readAdIdFromEvent` won't work.

Suggestion:
pass adId into click event listener instead of let it read from event.target.
code change
```  
  function loadClickTrackers(event, adId) {
    if (!adId) adId = readAdIdFromEvent(event);
    fireTracker(adId, 'click');
  }

  function attachClickListeners(adElements, listener = loadClickTrackers) {
    adElements = adElements || findAdElements(AD_ANCHOR_CLASS_NAME);

    for (let i = 0; i < adElements.length; i++) {
      let adId = readAdIdFromSingleElement(adElements[i]);
      adElements[i].addEventListener('click', function(event) {
        listener(event, adId);
      }, true);
    }
  }
```
