### ISSUE TITLE
Mediatype video support for secure creatives

### ISSUE THREAD

**Issue by adriafolchmrf** [prebid/prebid-universal-creative#89]
Hi,

We were checking if there was the possibility to display outstream video format inside secure creatives and found that in renderingManager.js there is a piece of code that basically skips the render if the mediatype is video.

`if (adObject.mediaType === 'video') {
          console.log('Error trying to write ad.');
        } `

https://github.com/prebid/prebid-universal-creative/blob/f62f781d69d645876efc51dca8f3d3da7da0058f/src/renderingManager.js#L118

Are there any plans to support this in the future? Or there is a reason to not currently support it?

Thanks

**Comment by mkendall07** [comment]
Hi @adriafolchmrf 
I thought outstream worked with SafeFrame/UC. Paging @jsnellbaker to take a look at this one.

**Comment by jsnellbaker** [comment]
@adriafolchmrf Sorry about the delay here.  I took a look at some outsream test pages we had that would invoke this cross domain code.

The reason it's not required here in this code for outstream video, is that the creative is actually rendered by Prebid.js rather than Prebid Universal Creative.  

https://github.com/prebid/Prebid.js/blob/master/src/secureCreatives.js#L68
In this file, there's a check to detect if the bid has a `renderer` defined, which is a sign that it's an outstream type ad.  

If it's detected, then Prebid.js immediately executes the `renderer` in order to display the ad.  

Prebid.js doesn't fire back a postMessage to give the bid data to PUC, so the callback code linked above doesn't actually execute in this type of scenario.

So you running outstream in a secure environment with Prebid Universal Creative should work fine.  Please let me know if you have any questions on the above.

Thanks.

**Comment by bretg** [comment]
Outstream renderers don't use the ad server's iframe. Closing this.
