### ISSUE TITLE
Add px to div's width and height

### ISSUE THREAD

**Issue by gvan** [prebid/prebid-universal-creative#98]
**Describe the bug**
Prebid universal creative gets sizes from backend and sets it to div without px, so div is not sized. If my banner doesn't specify sizes in px and uses width/height=100% instead, then banner is sized to 0x0. When I add 'px' to Prebid universal creative div's width and height then banner is sized as expected. My suggestion is to add px to div's width and height. As I see it should be added in constructMarkup function from renderingManager.js

**To Reproduce**
- create a banner without explicit sizes
- Prebid server returns this banner and sizes, for example, w: 308 and h: 425
- setup Prebid Android SDK with DFP's PublisherAdView
- no banner appears in the app
- look in chrome://inspect and see that Prebid setup div with width:308 and height:425
- manually add px to sizes, so we get width:308px and  height:425px
- banner appears in the app

**Expected behavior**
Banner renders with size returned from backend.

**Screenshots**
<img width="876" alt="Screenshot 2020-04-01 at 11 00 08" src="https://user-images.githubusercontent.com/3866569/78117180-00341980-740e-11ea-9651-a1699df514b9.png">

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android 9
 - Browser DFP's WebView

**Comment by arneschulz1984** [comment]
Hi, we run into the same Issue. With a APP -> PrebidServer (Hosted by AppNexus) Setup.

After having a look at the renderingManager.js i think the Problem is:

`/**
   * Wrap mobile app creative in div
   * @param {string} ad html for creative
   * @param {Number} width width of creative
   * @param {Number} height height of creative
   * @returns {string} creative markup
   */
  function constructMarkup(ad, width, height) {
    let id = utils.getUUID();
    return `<div id="${id}" style="border-style: none; position: absolute; width:100%; height:100%;">
      <div id="${id}_inner" style="margin: 0 auto; width:${width}; height:${height}; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">${ad}</div>
      </div>`;
  }`

For width and height is a number expected, but at the style is only set "width:${width}; height:${height};"
-> There should be added a "px"

For us it is not possible to add a "px" before because the constructMarkup is called from responseCallback where the width and height is parsed from a bidResponse:
`/**
   * Cache request Callback to display creative
   * @param {Bool} isMobileApp
   * @param {string} hbPb final price of the winning bid
   * @returns {function} a callback function that parses response
   */
  function responseCallback(isMobileApp, hbPb) {
    return function(response) {
      let bidObject = parseResponse(response);
      let ad = utils.getCreativeCommentMarkup(bidObject);
      let width = (bidObject.width) ? bidObject.width : bidObject.w;
      let height = (bidObject.height) ? bidObject.height : bidObject.h;

........
  };`

Now the Problem with a PrebidServer setup and OpenRTB-Spec is that "w" and "h" are INT values.

Can someone Help?

**Comment by arneschulz1984** [comment]
Link to Pull-Request for this Issue:
https://github.com/prebid/prebid-universal-creative/pull/121

**Comment by bretg** [comment]
Closed with #121
